board/urls.py
from django.urls import path

from .views import base_views, discussion_views, answer_views, vote_views

app_name = 'board'

urlpatterns = [
    # base_views.py
    path('',
         base_views.index, name='index'),
    path('<int:discussion_id>/',
         base_views.detail, name='detail'),

    # discussion_views.py
    path('discussion/create/',
         discussion_views.discussion_create, name='discussion_create'),
    path('discussion/modify/<int:discussion_id>/',
         discussion_views.discussion_modify, name='discussion_modify'),
    path('discussion/delete/<int:discussion_id>/',
         discussion_views.discussion_delete, name='discussion_delete'),

    # answer_views.py
    path('answer/create/<int:discussion_id>/',
         answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/',
         answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/',
         answer_views.answer_delete, name='answer_delete'),

    # vote_views.py
    path('vote/discussion/<int:discussion_id>/', vote_views.vote_discussion, name='vote_discussion'),
    path('vote/answer/<int:answer_id>/', vote_views.vote_answer, name='vote_answer'),
]

common/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy

from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('profile/', views.profile, name='profile'),
    path('signup/', views.signup, name='signup'),
    path('password_change/', auth_views.PasswordChangeView.as_view(success_url=reverse_lazy('common:profile'), template_name='common/password_change.html'), name='password_change'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from board.views import base_views
from stockpredapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('board/', include('board.urls')),
    path('common/', include('common.urls')),
    path('board', base_views.index, name='index'),
    path('stockpredapp/', include('stockpredapp.urls')),
    path('', views.main_loading)

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

common/models.py
from django.contrib.auth.models import User
from django.core import validators
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.deconstruct import deconstructible
from django.utils.translation import gettext_lazy as _


@deconstructible
class UnicodeNicknameValidator(validators.RegexValidator):
    regex = r'^[\w.@+-]+\Z'
    message = _(
        'Enter a valid nickname. This value may contain only letters, '
        'numbers, and @/./+/-/_ characters.'
    )
    flags = 0


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nickname_validator = UnicodeNicknameValidator()
    nickname = models.CharField(
        _('nickname'),
        max_length=10,
        unique=False,
        help_text=_('Required. 10 characters or fewer. Letters, digits and @/./+/-/_ only.'),
        validators=[nickname_validator],
        error_messages={
            'unique': _("A user with that nickname already exists."),
        },
    )
    STOCK_FIRM_CHOICE = (
        ('키움증권', 'KIWOOM'),
        ('삼성증권', 'SAMSUNG'),
        ('한국투자증권', 'KOREA'),
        ('KB증권', 'KOOKMIN'),
        ('NH투자증권', 'NONGHYUP'),
        ('미래에셋증권', 'MIREA'),
        ('신한금융투자', 'SHINHAN'),
        ('그 외', 'ETC')
    )
    stock_firm = models.CharField(choices=STOCK_FIRM_CHOICE, max_length=10)


@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    nickname = forms.CharField(max_length=20)
    email = forms.EmailField(label="이메일")
    STOCK_FIRM_CHOICE = (
        ('키움증권', 'KIWOOM'),
        ('삼성증권', 'SAMSUNG'),
        ('한국투자증권', 'KOREA'),
        ('KB증권', 'KOOKMIN'),
        ('NH투자증권', 'NONGHYUP'),
        ('미래에셋증권', 'MIREA'),
        ('신한금융투자', 'SHINHAN'),
        ('그 외', 'ETC')
    )
    stock_firm = forms.ChoiceField(choices=STOCK_FIRM_CHOICE)

    class Meta:
        model = User
        fields = ('username', 'nickname', 'email', 'password1', 'password2', 'stock_firm')


class UpdateForm(UserChangeForm):
    password = None
    nickname = forms.CharField(max_length=20)
    email = forms.EmailField(label="이메일")
    STOCK_FIRM_CHOICE = (
        ('키움증권', 'KIWOOM'),
        ('삼성증권', 'SAMSUNG'),
        ('한국투자증권', 'KOREA'),
        ('KB증권', 'KOOKMIN'),
        ('NH투자증권', 'NONGHYUP'),
        ('미래에셋증권', 'MIREA'),
        ('신한금융투자', 'SHINHAN'),
        ('그 외', 'ETC')
    )
    stock_firm = forms.ChoiceField(choices=STOCK_FIRM_CHOICE)

    class Meta:
        model = User
        fields = ('nickname', 'stock_firm')

common/views.py
from django.conf import settings
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from .forms import SignUpForm, UpdateForm
from .models import Profile


@login_required
def profile(request):
    """
    profile
    """
    profile_list = Profile.objects.order_by()
    context = {'profile_list': profile_list}
    return render(request, 'common/profile.html', context)


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.refresh_from_db()
            user.profile.nickname = form.cleaned_data.get('nickname')
            user.profile.stock_firm = form.cleaned_data.get('stock_firm')
            user.save()
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=user.username, password=raw_password)
            login(request, user)
            return redirect(settings.LOGIN_URL)
    else:
        form = SignUpForm()
    return render(request, 'common/signup.html', {'form': form})


@login_required(login_url='common:login')
def profile_update(request):
    """
    profile 수정
    """
    print(request.method)
    # test = get_object_or_404(Profile, pk=1)
    if request.method == 'POST':
        print("test1")
        form = UpdateForm(request.POST)
        if form.is_valid():
            print("test2")
            user = form.save()
            user.profile.nickname = form.cleaned_data('nickname')
            user.profile.stock_firm = form.cleaned_data('stock_firm')
            return redirect('common:profile')
    else:
        form = UpdateForm()
        print("test3")
    return render(request, 'common/profile_update.html', {'form': form})


@login_required(login_url='common:login')
def profile_delete(request):
    """
    profile 삭제
    """
    profile.delete()
    return redirect('board:index')

templates/common/login.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <div class="row">
        <div class="col-4">
            <h4>로그인</h4>
        </div>
        <div class="col-9 text-right">
            <span>계정이 없으세요? <a href="{% url 'common:signup' %}">Join us</a></span>
        </div>
    </div>
    <form method="post" class="post-form" action="{% url 'common:login' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="username" class="form-label mt-4">ID</label>
            <input type="text" class="form-control" name="username" id="username" placeholder="Username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password" class="form-label mt-4">PASSWORD</label>
            <input type="password" class="form-control" name="password" id="password" placeholder="Password">
        </div>
        <br>
        <button type="submit" class="btn btn-primary">Log In</button>
    </form>
</div>
{% endblock %}

templates/common/password_change.html
{% extends "base.html" %}

{% block content %}
<div class="container my-3">
    <div class="row my-3">
        <div class="col-4">
            <h2>비밀번호 변경</h2>
        </div>
            <form action="" method="post">
                {% csrf_token %}
                <table>
                    {{ form.as_table }}
                </table>
                <input type="submit" />
            </form>
        </div>
</div>
{% endblock %}

templates/common/profile.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <div class="row my-3">
        <div class="col-4">
            <h2>{{ user.username }}'s Profile</h2>
        </div>
        <p>
        <div><a href="{% url 'common:password_change' %}">비밀번호 변경</a></div>
        <p>
        <br>
        <div><strong>Email</strong></div>
        {{ user.email|default:"&dash;" }}
        <p>
        <div><strong>Nickname</strong></div>
        {{ user.profile.nickname|default:"&dash;" }}
        <p>
        <div><strong>증권사</strong></div>
        {{ user.profile.stock_firm|default:"&dash;" }}
    </div>
</div>
{% endblock %}

templates/common/signup.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <div class="row my-3">
        <div class="col-4">
            <h4>계정 생성</h4>
        </div>
        <div class="col-9 text-right">
            <span>이미 계정이 있으신가요? <a href="{% url 'common:login' %}">Log in</a></span>
        </div>
    </div>
    <form method="post" class="post-form" action="{% url 'common:signup' %}" >
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="username" class="form-label mt-4">Username</label>
            <input type="text" class="form-control" name="username" id="username" placeholder="Username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="email" class="form-label mt-4">Email address</label>
            <input type="text" class="form-control" name="email" id="email" placeholder="Enter email"
                    value="{{ form.email.value|default_if_none:'' }}">
            <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
        </div>
        <div class="form-group">
            <label for="nickname" class="form-label mt-4">Nickname</label>
            <input type="text" class="form-control" name="nickname" id="nickname" placeholder="Nickname"
                   value="{{ form.nickname.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password1" class="form-label mt-4">Password</label>
            <input type="password" class="form-control" name="password1" id="password1" placeholder="Password">
        </div>
        <div class="form-group">
            <label for="password2" class="form-label mt-4">Password Check</label>
            <input type="password" class="form-control" name="password2" id="password2" placeholder="Password">
        </div>
        <div class="form-group">
            <label for="stock_firm" class="form-label mt-4">증권사</label>
            <select class="form-select" id="stock_firm" name="stock_firm">
                <option>키움증권</option>
                <option>삼성증권</option>
                <option>한국투자증권</option>
                <option>KB증권</option>
                <option>미래에셋증권</option>
                <option>신한금융투자</option>
                <option>그 외</option>
            </select>
        </div>
        <br>
        <button type="submit" class="btn btn-primary">Sign up</button>
    </form>
</div>
{% endblock %}