board/urls.py
from django.urls import path

from .views import base_views, discussion_views, answer_views, vote_views

app_name = 'board'

urlpatterns = [
    # base_views.py
    path('',
         base_views.index, name='index'),
    path('<int:discussion_id>/',
         base_views.detail, name='detail'),

    # discussion_views.py
    path('discussion/create/',
         discussion_views.discussion_create, name='discussion_create'),
    path('discussion/modify/<int:discussion_id>/',
         discussion_views.discussion_modify, name='discussion_modify'),
    path('discussion/delete/<int:discussion_id>/',
         discussion_views.discussion_delete, name='discussion_delete'),

    # answer_views.py
    path('answer/create/<int:discussion_id>/',
         answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/',
         answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/',
         answer_views.answer_delete, name='answer_delete'),

    # vote_views.py
    path('vote/discussion/<int:discussion_id>/', vote_views.vote_discussion, name='vote_discussion'),
    path('vote/answer/<int:answer_id>/', vote_views.vote_answer, name='vote_answer'),
]

common/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy

from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('profile/', views.profile, name='profile'),
    path('signup/', views.signup, name='signup'),
    path('password_change/', auth_views.PasswordChangeView.as_view(success_url=reverse_lazy('common:profile'), template_name='common/password_change.html'), name='password_change'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from board.views import base_views
from stockpredapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('board/', include('board.urls')),
    path('common/', include('common.urls')),
    path('board', base_views.index, name='index'),
    path('stockpredapp/', include('stockpredapp.urls')),
    path('', views.main_loading)

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stockpredapp/urls.py
from django.urls import path

from . import views

app_name = 'stockpredapp'

urlpatterns = [
    path('', views.s_index, name='s_index'),
    path('<int:stock_id>/', views.result, name='result'),
    path('loading/<int:stock_id>/', views.loading, name='loading'),
    path('jisu/', views.jisu, name='jisu'),
    path('main_loading/', views.main_loading, name='main_loading'),
    path('main_loading2/', views.main_loading2, name='main_loading2'),
    path('random_pred/', views.random_pred, name='random_pred'),



]

board/views/base_views.py
from django.core.paginator import Paginator
from django.db.models import Q, Count
from django.shortcuts import render, get_object_or_404

from ..apps import get_client_ip
from ..models import Discussion, DiscussionCount


def index(request):
    """
    Discussion_list 출력
    """
    # 입력 파라미터
    page = request.GET.get('page', '1')  # 페이지
    kw = request.GET.get('kw', '')  # 검색어
    so = request.GET.get('so', 'recent')

    if so == 'recommend':
        discussion_list = Discussion.objects.annotate(num_voter=Count('voter')).order_by('-num_voter', '-create_date')
    elif so == 'popular':
        discussion_list = Discussion.objects.annotate(num_answer=Count('answer')).order_by('-num_answer',
                                                                                           '-create_date')
    elif so == 'cntview':
        discussion_list = Discussion.objects.order_by('-view_count', '-create_date')
    else:  # recent
        discussion_list = Discussion.objects.order_by('-create_date')

    # 조회
    if kw:
        discussion_list = discussion_list.filter(
            Q(subject__icontains=kw) |  # 제목검색
            Q(content__icontains=kw) |  # 내용검색
            Q(author__username__icontains=kw)  # 질문 글쓴이검색
            # Q(answer__author__username__icontains=kw)   # 답변 글쓴이검색
        ).distinct()

    # 페이징처리
    paginator = Paginator(discussion_list, 10)
    page_obj = paginator.get_page(page)

    context = {'discussion_list': page_obj, 'page': page, 'kw': kw, 'so': so}
    return render(request, 'board/discussion_list.html', context)


def detail(request, discussion_id):
    """
    Discussion_context 출력
    """
    discussion = get_object_or_404(Discussion, pk=discussion_id)
    context = {'discussion': discussion}

    ip = get_client_ip(request)
    cnt = DiscussionCount.objects.filter(ip=ip, discussion=discussion).count()
    if cnt == 0:
        qc = DiscussionCount(ip=ip, discussion=discussion)
        qc.save()
        if discussion.view_count:
            discussion.view_count += 1
        else:
            discussion.view_count = 1
        discussion.save()

    return render(request, 'board/discussion_detail.html', context)

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <link rel="stylesheet" href="../_assets/css/custom.min.css">
    <!-- style CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>stock_pred</title>
</head>
<body>
{% include "navbar.html" %}
{% block content %}
{% endblock %}
<!-- jQuery JS -->
<script src="{% static 'jquery-3.6.0.min.js' %}"></script>
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
<!-- 자바스크립트 Start -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->
<br><br><br><br><br>
<!-- 출처 -->
      <footer id="footer">
        <div class="row">
          <div class="col-lg-12">
            <ul class="list-unstyled">
              <li class="float-end"><a href="#top">Back to top</a></li>
              <li><a href="https://github.com/id-gxon/investment-analysis.git">GitHub</a></li>
<!--              <li><a href="../help/#api">API</a></li>-->
            </ul>
            <p>Made by <a href="https://github.com/id-gxon/">김건우</a>
                    <a href="https://github.com/junnng">이현정</a>
                    <a href="https://github.com/Ddongh">박동혁</a>
                    <a href="https://github.com/dabokkim">김다복</a>
            </p>
            <p>Based on <a href="https://getbootstrap.com/" rel="nofollow">Bootstrap</a>.
                Icons from <a href="https://fontawesome.com/" rel="nofollow">Font Awesome</a>.
                Web fonts from <a href="https://fonts.google.com/" rel="nofollow">Google</a>.</p>
              <p class="text-warning"><strong>※StockPred의 예측을 바탕으로 매매/매도한 유저의 주식 결과는 책임지지 않습니다.</strong></p>
          </div>
        </div>
      </footer>
</body>
</html>

templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% if user.is_authenticated %}
    <a href="{% url 'common:profile' %}">{{ user }}</a>
    <a href="{% url 'common:logout' %}?next={{ request.path }}" onclick="return confirm('Are you sure?');">로그아웃</a>
    {% else %}
    회원가입
    <a href="{% url 'common:login' %}">로그인</a>
    {% endif %}
    <hr/>
    {% block content %}
    {% endblock %}
</body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'stockpredapp:main_loading2' %}">Stock Pred</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01"
            aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav me-auto">
            <li class="nav-item ">
                {% if user.is_authenticated %}
                <a class="nav-link active" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
                {% else %}
                <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                {% endif %}
                <span class="visually-hidden">(current)</span>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{% url 'stockpredapp:s_index' %}">종목 분석</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{% url 'board:index' %}">토론방</a>
            </li>
            <li class="nav-item ">
                {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'common:profile' %}">내 정보 확인</a>
                {% else %}
                <a></a>
                {% endif %}
            </li>
        </ul>
    </div>
    </div>
</nav>