board/urls.py
from django.urls import path

from .views import base_views, discussion_views, answer_views, vote_views

app_name = 'board'

urlpatterns = [
    # base_views.py
    path('',
         base_views.index, name='index'),
    path('<int:discussion_id>/',
         base_views.detail, name='detail'),

    # discussion_views.py
    path('discussion/create/',
         discussion_views.discussion_create, name='discussion_create'),
    path('discussion/modify/<int:discussion_id>/',
         discussion_views.discussion_modify, name='discussion_modify'),
    path('discussion/delete/<int:discussion_id>/',
         discussion_views.discussion_delete, name='discussion_delete'),

    # answer_views.py
    path('answer/create/<int:discussion_id>/',
         answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/',
         answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/',
         answer_views.answer_delete, name='answer_delete'),

    # vote_views.py
    path('vote/discussion/<int:discussion_id>/', vote_views.vote_discussion, name='vote_discussion'),
    path('vote/answer/<int:answer_id>/', vote_views.vote_answer, name='vote_answer'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from board.views import base_views
from stockpredapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('board/', include('board.urls')),
    path('common/', include('common.urls')),
    path('board', base_views.index, name='index'),
    path('stockpredapp/', include('stockpredapp.urls')),
    path('', views.main_loading)

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

board/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class Discussion(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_discussion')
    subject = models.CharField(max_length=200)
    content = models.TextField()
    image = models.ImageField(null=True, blank=True, upload_to="images/")
    create_date = models.DateTimeField(auto_now_add=True)
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User)
    view_count = models.IntegerField(default=0)

    def __str__(self):
        return self.subject

    def get_absolute_url(self):
        return reverse('board: discussion_detail', args=[str(self.id)])


class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_answer')
    discussion = models.ForeignKey(Discussion, on_delete=models.CASCADE)
    content = models.TextField()
    image = models.ImageField(null=True, blank=True)
    create_date = models.DateTimeField(auto_now_add=True)
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_answer')


class DiscussionCount(models.Model):
    ip = models.CharField(max_length=30)
    discussion = models.ForeignKey(Discussion, on_delete=models.CASCADE)

    def __unicode__(self):
        return self.ip

board/forms.py
from django import forms

from board.models import Discussion, Answer


class DiscussionForm(forms.ModelForm):
    class Meta:
        model = Discussion  # 사용할 모델
        fields = ['subject', 'content']
        widgets = {
            'subject': forms.TextInput(attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 10}),
        }
        labels = {
            'subject': '제목',
            'content': '내용',
        }


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content', 'image']
        widgets = {
            'subject': forms.TextInput(attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 10})
        }
        labels = {
            'content': '답글내용',
            'image': '사진',
        }

board/views/answer_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone

from ..forms import AnswerForm
from ..models import Discussion, Answer


@login_required(login_url='common:login')
def answer_create(request, discussion_id):
    """
    Discussion_answer 등록
    """
    discussion = get_object_or_404(Discussion, pk=discussion_id)

    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.create_date = timezone.now()
            answer.discussion = discussion
            answer.save()
            return redirect('{}#answer_{}'.format(
                resolve_url('board:detail', discussion_id=discussion.id), answer.id))
    else:
        form = AnswerForm()

    context = {'discussion': discussion, 'form': form}
    return render(request, 'board/discussion_detail.html', context)


@login_required(login_url='common:login')
def answer_modify(request, answer_id):
    """
    discussion_answer 수정
    """
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '수정 권한이 없습니다.')
        return redirect('board:detail', discussion_id=answer.discussion.id)

    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.modify_date = timezone.now()
            answer.save()
            return redirect('{}#answer_{}'.format(
                resolve_url('board:detail', discussion_id=answer.discussion.id), answer.id))
    else:
        form = AnswerForm(instance=answer)

    context = {'answer': answer, 'form': form}
    return render(request, 'board/answer_form.html', context)


@login_required(login_url='common:login')
def answer_delete(request, answer_id):
    """
    discussion_answer 삭제
    """
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '삭제 권한이 없습니다.')
    else:
        answer.delete()
    return redirect('board:detail', discussion_id=answer.discussion.id)

board/views/base_views.py
from django.core.paginator import Paginator
from django.db.models import Q, Count
from django.shortcuts import render, get_object_or_404

from ..apps import get_client_ip
from ..models import Discussion, DiscussionCount


def index(request):
    """
    Discussion_list 출력
    """
    # 입력 파라미터
    page = request.GET.get('page', '1')  # 페이지
    kw = request.GET.get('kw', '')  # 검색어
    so = request.GET.get('so', 'recent')

    if so == 'recommend':
        discussion_list = Discussion.objects.annotate(num_voter=Count('voter')).order_by('-num_voter', '-create_date')
    elif so == 'popular':
        discussion_list = Discussion.objects.annotate(num_answer=Count('answer')).order_by('-num_answer',
                                                                                           '-create_date')
    elif so == 'cntview':
        discussion_list = Discussion.objects.order_by('-view_count', '-create_date')
    else:  # recent
        discussion_list = Discussion.objects.order_by('-create_date')

    # 조회
    if kw:
        discussion_list = discussion_list.filter(
            Q(subject__icontains=kw) |  # 제목검색
            Q(content__icontains=kw) |  # 내용검색
            Q(author__username__icontains=kw)  # 질문 글쓴이검색
            # Q(answer__author__username__icontains=kw)   # 답변 글쓴이검색
        ).distinct()

    # 페이징처리
    paginator = Paginator(discussion_list, 10)
    page_obj = paginator.get_page(page)

    context = {'discussion_list': page_obj, 'page': page, 'kw': kw, 'so': so}
    return render(request, 'board/discussion_list.html', context)


def detail(request, discussion_id):
    """
    Discussion_context 출력
    """
    discussion = get_object_or_404(Discussion, pk=discussion_id)
    context = {'discussion': discussion}

    ip = get_client_ip(request)
    cnt = DiscussionCount.objects.filter(ip=ip, discussion=discussion).count()
    if cnt == 0:
        qc = DiscussionCount(ip=ip, discussion=discussion)
        qc.save()
        if discussion.view_count:
            discussion.view_count += 1
        else:
            discussion.view_count = 1
        discussion.save()

    return render(request, 'board/discussion_detail.html', context)

board/views/discussion_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from ..forms import DiscussionForm
from ..models import Discussion


@login_required(login_url='common:login')
def discussion_create(request):
    """
    discussion 등록
    """
    if request.method == 'POST':
        form = DiscussionForm(request.POST)
        if form.is_valid():
            discussion = form.save(commit=False)
            discussion.author = request.user
            discussion.create_date = timezone.now()
            try:
                discussion.image = request.FILES['image']
            except:
                discussion.image = None
            discussion.save()
            return redirect('board:index')
    else:
        form = DiscussionForm()

    context = {'form': form}
    return render(request, 'board/discussion_form.html', context)


@login_required(login_url='common:login')
def discussion_modify(request, discussion_id):
    """
    discussion 수정
    """
    discussion = get_object_or_404(Discussion, pk=discussion_id)
    if request.user != discussion.author:
        messages.error(request, '수정 권한이 없습니다.')
        return redirect('board:detail', discussion_id=discussion.id)

    if request.method == "POST":
        form = DiscussionForm(request.POST, instance=discussion)
        if form.is_valid():
            discussion = form.save(commit=False)
            discussion.modify_date = timezone.now()
            try:
                discussion.image = request.FILES['image']
            except:
                discussion.image = None
            discussion.save()
            return redirect('board:detail', discussion_id=discussion.id)
    else:
        form = DiscussionForm(instance=discussion)
    context = {'form': form}
    return render(request, 'board/discussion_form.html', context)


@login_required(login_url='common:login')
def discussion_delete(request, discussion_id):
    """
    discussion 삭제
    """
    discussion = get_object_or_404(Discussion, pk=discussion_id)
    if request.user != discussion.author:
        messages.error(request, '삭제 권한이 없습니다.')
        return redirect('board:detail', discussion_id=discussion.id)
    discussion.delete()
    return redirect('board:index')

board/views/vote_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect

from ..models import Discussion, Answer


@login_required(login_url='common:login')
def vote_discussion(request, discussion_id):
    """
    discussion_vote 등록
    """
    discussion = get_object_or_404(Discussion, pk=discussion_id)
    if request.user == discussion.author:
        messages.error(request, '본인이 작성한 글은 추천할 수 없습니다.')
    else:
        discussion.voter.add(request.user)
    return redirect('board:detail', discussion_id=discussion.id)


@login_required(login_url='common:login')
def vote_answer(request, answer_id):
    """
    discussion_answer_vote 등록
    """
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user == answer.author:
        messages.error(request, '본인이 작성한 글은 추천할 수 없습니다.')
    else:
        answer.voter.add(request.user)
    return redirect('board:detail', discussion_id=answer.discussion.id)

templates/board/answer_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-3">
    <form method="post" class="post-form">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="content">답글내용</label>
            <textarea class="form-control" name="content" id="content"
                      rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/board/discussion_detail.html
{% extends 'base.html' %}
{% load board_filter %}
{% block content %}
<div class="container my-3">
    <!-- 사용자 오류 표시 -->
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
    {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul><li>{{ message.message }}</li></ul>
    {% endfor %}
    </div>
    {% endif %}

    <h2 class="border-bottom py-2">
        {{ discussion.subject }}<h6>조회수: {{ discussion.view_count }}</h6>
    </h2>

    <div class="container">
        {% if discussion.image %}
            <img src="{{discussion.image.url}}" style="width:80%; height:400px">
            <br><br>
        {% endif %}
    </div>

    <div class="row my-3">
        <div class="col-1">
            <div class="bg-light text-center p-3 border font-weight-bolder mb-1">{{ discussion.voter.count }}</div>
            <a href="#" data-uri="{% url 'board:vote_discussion' discussion.id  %}"
               class="recommend btn btn-sm btn-secondary btn-block my-1">추천하기</a>
        </div>
        <div class="col-11">
            <div class="card">
                <div class="card-body">
                    <div class="card-text">{{ discussion.content|mark }}</div>
                    <div class="d-flex justify-content-end">
                        {% if discussion.modify_date %}
                        <div class="badge rounded-pill bg-light p-2 text-left mx-3">
                            <div class="mb-2">modified at</div>
                            <div>{{ discussion.modify_date }}</div>
                        </div>
                        {% endif %}

                        <div class="badge rounded-pill bg-light">
                            <div class="mb-2">{{ discussion.author.username }}</div>
                            <div>{{ discussion.create_date }}</div>
                        </div>
                    </div>
                    {% if request.user == discussion.author %}
                    <div class="my-3">
                        <a href="{% url 'board:discussion_modify' discussion.id  %}"
                       class="btn btn-sm btn-outline-secondary">수정하기</a>
                        <a href="#" class="delete btn btn-sm btn-outline-secondary"
                           data-uri="{% url 'board:discussion_delete' discussion.id  %}">삭제하기</a>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <h5 class="border-bottom my-3 py-2">{{discussion.answer_set.count}}개의 답변이 있습니다.</h5>
    {% for answer in discussion.answer_set.all %}
    <a name="answer_{{ answer.id }}"></a>
    <div class="row my-3">
        <div class="col-1">
            <div class="bg-light text-center p-3 border font-weight-bolder mb-1">{{answer.voter.count}}</div>
            <a href="#" data-uri="{% url 'board:vote_answer' answer.id  %}"
            class="recommend btn btn-sm btn-secondary btn-block my-1">추천하기</a>
        </div>
        <div class="col-11">
            <div class="card">
                <div class="card-body">
                    <div class="card-text">{{ answer.content|mark }}</div>
                    <div class="d-flex justify-content-end">
                        {% if answer.modify_date %}
                        <div class="badge rounded-pill bg-light text-left mx-3">
                            <div class="mb-2">modified at</div>
                            <div>{{ answer.modify_date }}</div>
                        </div>
                        {% endif %}
                        <div class="badge rounded-pill bg-light">
                            <div class="mb-2">{{ answer.author.username }}</div>
                            <div>{{ answer.create_date }}</div>
                        </div>
                    </div>
                    {% if request.user == answer.author %}
                    <div class="my-3">
                        <a href="{% url 'board:answer_modify' answer.id  %}"
                        class="btn btn-sm btn-outline-secondary">수정하기</a>
                        <a href="#" class="delete btn btn-sm btn-outline-secondary"
                            data-uri="{% url 'board:answer_delete' answer.id  %}">삭제하기</a>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <form action="{% url 'board:answer_create' discussion.id %}" method="post" class="my-3">
        {% csrf_token %}
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
        {% for field in form %}
            {% if field.errors %}
            <strong>{{ field.label }}</strong>
            {{ field.errors }}
            {% endif %}
        {% endfor %}
        </div>
        {% endif %}
        <div class="form-group">
            <textarea {% if not user.is_authenticated %}disabled{% endif %}
              name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <br>
        <input type="submit" value="답글등록" class="btn btn-primary">
    </form>
</div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $(".delete").on('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = $(this).data('uri');
        }
    });
    $(".recommend").on('click', function() {
        if(confirm("정말로 추천하시겠습니까?")) {
            location.href = $(this).data('uri');
        }
    });
});
</script>
{% endblock %}

templates/board/discussion_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">토론 글 등록</h5>
    <form method="post" class="post-form my-3" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label for="subject">제목</label>
            <input type="text" class="form-control" name="subject" id="subject"
                   value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="content" class="form-label mt-4">내용</label>
            <textarea class="form-control" name="content"
                      id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <div class="form-group">
            <label for="image" class="form-label mt-4">이미지 첨부</label>
            <input class="form-control" type="file" name="image" id="image">
        </div>
        <br>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/board/discussion_list.html
{% extends 'base.html' %}
{% load board_filter %}
{% block content %}
<div class="container my-3">
    <div class="row justify-content-end my-3">
        <div class="col-4 input-group">
            <input type="text" class="form-control kw me-sm-2 " value="{{ kw|default_if_none:'' }}" >
            <div class="input-group-append">
               <button class="btn btn-secondary my-2 my-sm-0" type="submit" id="btn_search">Search</button>
            </div>
        </div>
    </div>
    <div class="row justify-content-front my-3">
        <div class="col-2">
            <select class="form-control so">
                <option value="recent" {% if so == 'recent' %}selected{% endif %}>최신순</option>
                <option value="recommend" {% if so == 'recommend' %}selected{% endif %}>추천순</option>
                <option value="popular" {% if so == 'popular' %}selected{% endif %}>인기순</option>
                <option value="cntview" {% if so == 'cntview' %}selected{% endif %}>조회순</option>
            </select>
        </div>
    </div>
    <table class="table">
        <thead>
        <tr class="text-center table-secondary">
            <th>번호</th>
            <th>추천</th>
            <th style="width:40%">제목</th>
            <th>작성자</th>
            <th>작성일시</th>
            <th>조회수</th>
        </tr>
        </thead>
        <tbody>
        {% if discussion_list %}
        {% for discussion in discussion_list %}
        <tr class>
            <td class="text-center">
                {{ discussion_list.paginator.count|sub:discussion_list.start_index|sub:forloop.counter0|add:1 }}
            </td>
            <td class="text-center">
                {% if discussion.voter.all.count > 0 %}
                <span class>{{ discussion.voter.all.count }}</span>
                {% endif %}
            </td>
            <td class="text-left">
                <a href="{% url 'board:detail' discussion.id %}">{{ discussion.subject }}</a>
                {% if discussion.answer_set.count > 0 %}
                <span class="text-danger small ml-2">{{ discussion.answer_set.count }}</span>
                {% endif %}
            </td>
            <td class="text-center">{{ discussion.author.username }}</td>
            <td class="text-center">{{ discussion.create_date }}</td>
            <td class="text-center">{{ discussion.view_count }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr class="text-center">
            <td colspan="7">토론 글이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if discussion_list.has_previous %}
        <li class="page-item">
            <a class="page-link" data-page="{{ discussion_list.previous_page_number }}" href="#">이전</a>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in discussion_list.paginator.page_range %}
        {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}
            {% if page_number == discussion_list.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" data-page="{{ page_number }}" href="#">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" data-page="{{ page_number }}" href="#">{{ page_number }}</a>
            </li>
            {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if discussion_list.has_next %}
        <li class="page-item">
            <a class="page-link" data-page="{{ discussion_list.next_page_number }}" href="#">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
    <a href="{% url 'board:discussion_create' %}" class="btn btn-primary">토론 등록하기</a>
</div>
<form id="searchForm" method="get" action="{% url 'index' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
    <input type="hidden" id="so" name="so" value="{{ so }}">
</form>
{% endblock %}
{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $(".page-link").on('click', function() {    // 이전버튼(page-link) 클릭 시 아래 스크립트 실행
        $("#page").val($(this).data("page"));
        $("#searchForm").submit();
    });

    $("#btn_search").on('click', function() {   // 검색버튼 클릭 시 아래 스크립트 실행
        $("#kw").val($(".kw").val());
        $("#page").val(1); // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
        $("#searchForm").submit();
    });

    $(".so").on('change', function() {
        $("#so").val($(this).val());
        $("#page").val(1);
        $("#searchForm").submit();
    });
});
</script>
{% endblock %}