board/urls.py
from django.urls import path

from .views import base_views, discussion_views, answer_views, vote_views

app_name = 'board'

urlpatterns = [
    # base_views.py
    path('',
         base_views.index, name='index'),
    path('<int:discussion_id>/',
         base_views.detail, name='detail'),

    # discussion_views.py
    path('discussion/create/',
         discussion_views.discussion_create, name='discussion_create'),
    path('discussion/modify/<int:discussion_id>/',
         discussion_views.discussion_modify, name='discussion_modify'),
    path('discussion/delete/<int:discussion_id>/',
         discussion_views.discussion_delete, name='discussion_delete'),

    # answer_views.py
    path('answer/create/<int:discussion_id>/',
         answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/',
         answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/',
         answer_views.answer_delete, name='answer_delete'),

    # vote_views.py
    path('vote/discussion/<int:discussion_id>/', vote_views.vote_discussion, name='vote_discussion'),
    path('vote/answer/<int:answer_id>/', vote_views.vote_answer, name='vote_answer'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from board.views import base_views
from stockpredapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('board/', include('board.urls')),
    path('common/', include('common.urls')),
    path('board', base_views.index, name='index'),
    path('stockpredapp/', include('stockpredapp.urls')),
    path('', views.main_loading)

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stockpredapp/urls.py
from django.urls import path

from . import views

app_name = 'stockpredapp'

urlpatterns = [
    path('', views.s_index, name='s_index'),
    path('<int:stock_id>/', views.result, name='result'),
    path('loading/<int:stock_id>/', views.loading, name='loading'),
    path('jisu/', views.jisu, name='jisu'),
    path('main_loading/', views.main_loading, name='main_loading'),
    path('main_loading2/', views.main_loading2, name='main_loading2'),
    path('random_pred/', views.random_pred, name='random_pred'),



]

stockpredapp/models.py
from django.db import models


# Create your models here.


class Test(models.Model):  # db 테스트용
    created_date = models.DateTimeField(null=True)
    stock_code = models.CharField(max_length=200)
    stock_name = models.CharField(max_length=200)

    def __str__(self):
        return self.stock_name


class Code_name(models.Model):  # 크롤링한 종목코드와 종목이름
    created_date = models.DateTimeField(null=True)
    stock_code = models.CharField(max_length=200, null=True)  # 종목코드
    stock_name = models.CharField(max_length=200, null=True)  # 종목이름
    market = models.CharField(max_length=200, null=True, default='')  # 코스닥, 코스피 구분
    sector = models.CharField(max_length=200, null=True, default='')  # 사업분야
    industry = models.CharField(max_length=200, null=True, default='')  # 세부분야
    listing_date = models.CharField(max_length=200, null=True, default='')  # 상장일
    settle_month = models.CharField(max_length=200, null=True, default='')  #
    representative = models.CharField(max_length=200, null=True, default='')  # 대표
    homepage = models.CharField(max_length=200, null=True, default='')  # 홈페이지
    region = models.CharField(max_length=200, null=True, default='')  # 지역

    def __str__(self):
        return self.stock_name


class Rnn_data(models.Model):  # 사용자로부터 받은 데이터
    created_date = models.DateTimeField(null=True)
    user_id = models.CharField(null=True, max_length=200)  # 사용자 id
    stock_code = models.CharField(max_length=200)  # 종목코드
    stock_name = models.CharField(max_length=200)  # 종목이름

    start = models.DateField()  # 조회시작일
    end = models.DateField()  # 조회종료일


class Rnn_result(models.Model):  # 순환신경망 분석결과 저장
    created_date = models.DateTimeField(null=True)
    user_id = models.CharField(null=True, max_length=200)  # 사용자 id
    stock_code = models.CharField(max_length=200)  # 종목코드
    stock_name = models.CharField(max_length=200)  # 종목이름

    start = models.DateField()  # 조회시작일
    end = models.DateField()  # 조회종료일

    result_max = models.DecimalField(max_digits=10, decimal_places=2)  # 예측값을 최대값
    result_min = models.DecimalField(max_digits=10, decimal_places=2)  # 예측값의 최소값

    d1 = models.DecimalField(max_digits=10, decimal_places=2)  # n일 후 예측치
    d2 = models.DecimalField(max_digits=10, decimal_places=2)
    d3 = models.DecimalField(max_digits=10, decimal_places=2)
    d4 = models.DecimalField(max_digits=10, decimal_places=2)
    d5 = models.DecimalField(max_digits=10, decimal_places=2)
    d6 = models.DecimalField(max_digits=10, decimal_places=2)
    d7 = models.DecimalField(max_digits=10, decimal_places=2)

    train_RMSE = models.DecimalField(max_digits=10, decimal_places=2)  # train_data의 RMSE
    test_RMSE = models.DecimalField(max_digits=10, decimal_places=2)  # test_data의 RMSE

    def __str__(self):  # 조회할때 id 번호 대신 종목이름으로 보여주기
        return self.stock_name

# from stockpredapp.models import Code_name
# from django.utils import timezone
# import FinanceDataReader as fdr
#
# df = fdr.StockListing("KRX") # 한국 데이터 크롤링
# df = df.fillna('')
#
# for i in range(len(df)): # stock_data 크롤링
#     s = Code_name(
#         created_date=timezone.now(),
#         stock_code=df.iloc[i, 0],
#         market=df.iloc[i, 1],
#         stock_name=df.iloc[i, 2],
#         sector=df.iloc[i, 3],
#         industry=df.iloc[i, 4],
#         listing_date=df.iloc[i, 5],
#         settle_month=df.iloc[i, 6],
#         representative=df.iloc[i, 7],
#         homepage=df.iloc[i, 8],
#         region=df.iloc[i, 9])
#     s.save()
#
#
# import pandas as pd
# df_na = fdr.StockListing("NASDAQ") # 나스닥 # 외국 데이터 크롤링
# df_na['Market'] = 'NASDAQ'
# df_sp = fdr.StockListing("S&P500") # S&P500
# df_sp['Market'] = 'S&P500'
# df_ny = fdr.StockListing("NYSE") # 뉴욕 증권거래소
# df_ny['Market'] = 'NYSE'
# df_am = fdr.StockListing("AMEX") # 아메리카 증권거래소
# df_am['Market'] = 'AMEX'
#
# df = pd.concat([df_na, df_sp, df_ny, df_am])
# df = df.drop_duplicates(['Symbol'])
# df = df.fillna('')
#
# for i in range(len(df)):
#     s = Code_name(
#         created_date=timezone.now(),
#         stock_code=df.iloc[i, 0],
#         stock_name=df.iloc[i, 1],
#         industry = df.iloc[i, 2],
#         market = df.iloc[i, 4],
#         sector = df.iloc[i, 5],
#         )
#     s.save()

stockpredapp/views.py
# Create your views here.

from django.shortcuts import render
from django.core.paginator import Paginator
from .models import Code_name

from keras.models import Sequential
from keras.layers import SimpleRNN, Dense
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split

from django.db.models import Q
from datetime import datetime
from dateutil.relativedelta import relativedelta
import json
import math
import numpy as np
import FinanceDataReader as fdr
import time
import random


epochs = 100  # 학습반복수


def s_index(request):
    """
    종목 출력
    """
    page1 = request.GET.get('page1', '1')
    kw1 = request.GET.get('kw1', '')  # 검색어

    stock_list = Code_name.objects.order_by('created_date')
    if kw1:
        stock_list = stock_list.filter(
            Q(stock_name__icontains=kw1) | # 종목이름검색
            Q(stock_code__icontains=kw1) |# 종목코드검색
            Q(market__icontains=kw1) # 상장구분 검색
        ).distinct()

    # 페이징 처리
    paginator = Paginator(stock_list, 10)

    page_obj = paginator.get_page(page1)

    context = {'stock_list': page_obj, 'page1': page1, 'kw1': kw1}  # {'key' : value}
    return render(request, 'stockpredapp/stock_list.html', context)

# def result(request, stock_id):
#     '''
#     분석결과 출력
#     '''
#     #stock = Code_name.objects.get(id=stock_id)
#     stock = get_object_or_404(Code_name, pk=stock_id)
#     context = {'stock': stock}
#     return render(request, 'stockpredapp/stock_result.html', context)

# def loading(request, stock_id):
#     context = {'stock_id':stock_id}
#     return render(request, 'stockpredapp/loading.html', context)


def random_pred(request):
    random_stock = random.randrange(1,15782)
    stock = Code_name.objects.get(id=random_stock)
    market = Code_name.objects.get(id=random_stock).market
    context = {'random_stock':random_stock,
               'stock':stock,
               'market':market}
    return render(request, 'stockpredapp/random_pred.html', context)


def main_loading(request):
    return render(request, 'stockpredapp/main_loading.html')


def main_loading2(request):
    return render(request, 'stockpredapp/main_loading2.html')


def jisu(request):
    end = datetime.today() # 오늘 날짜
    start = end - relativedelta(months=1)
    start = start.strftime("%Y-%m-%d") # 문자열 변환
    end = end.strftime("%Y-%m-%d") # 문자열 변환

    kospi = fdr.DataReader(symbol='KS11', start=start, end=end).reset_index()  # 코스피 1년 데이터 클롤링
    kospi = kospi.loc[:, 'Close'] # 종가 데이터 추출
    kospi = list(kospi) # 리스트 변환
    kosdaq = fdr.DataReader(symbol='KQ11', start=start, end=end).reset_index()  # 코스닥 1년 데이터 크롤링

    date_kor = kosdaq.loc[:, 'Date']  # 날짜 데이터 추출
    date_kor = list(date_kor)
    for i in range(len(date_kor)):  # datetime -> str 변환
        date_kor[i] = date_kor[i].strftime("%Y-%m-%d")

    kosdaq = kosdaq.loc[:, 'Close']  # 종가 데이터 추출
    kosdaq = list(kosdaq)  # 리스트 변환
    dows = fdr.DataReader(symbol='DJI', start=start, end=end).reset_index()  # 다우지수
    dows = dows.loc[:, 'Close'] # 종가 데이터 추출
    dows = list(dows)  # 리스트 변환

    nasdaq = fdr.DataReader(symbol='IXIC', start=start, end=end).reset_index()  # 나스닥지수

    date_usa = nasdaq.loc[:, 'Date']  # 날짜 데이터 추출
    date_usa = list(date_usa)
    for i in range(len(date_usa)):  # datetime -> str 변환
        date_usa[i] = date_usa[i].strftime("%Y-%m-%d")

    nasdaq = nasdaq.loc[:, 'Close']  # 종가 데이터 추출
    nasdaq = list(nasdaq)  # 리스트 변환

    context = {'kospi':kospi,
               'kosdaq':kosdaq,
               'date_kor':date_kor,
               'date_usa':date_usa,
               'start':start,
               'end':end,
               'dows':dows,
               'nasdaq':nasdaq,
               # 'sp500':sp500
               }
    return render(request, 'stockpredapp/jisu.html', context)


def loading(request, stock_id):
    stock = Code_name.objects.get(id=stock_id)
    name = Code_name.objects.get(id=stock_id).stock_name
    market = Code_name.objects.get(id=stock_id).market
    context = {'stock':stock,
               'stock_id':stock_id,
               'name':name,
               'market':market}
    return render(request, 'stockpredapp/loading.html', context)


def result(request, stock_id):
    '''
    분석결과 출력
    '''

    stock = Code_name.objects.get(id=stock_id)
    name = Code_name.objects.get(id=stock_id).stock_code
    end = datetime.today()
    start = end - relativedelta(months=12)
    start = start.strftime("%Y-%m-%d")
    end = end.strftime("%Y-%m-%d")
    try:
        Result = rnn(name, start=start, end=end)
        result = Result[0]  # rnn 함수결과를 변수에 할당
        result_d1 = Result[1]
        result_d2 = Result[2]
        result_d3 = Result[3]
        result_d4 = Result[4]
        result_d5 = Result[5]
        result_d6 = Result[6]
        result_d7 = Result[7]
        result_max = Result[8]
        result_min = Result[9]
        train_RMSE = Result[10]
        test_RMSE = Result[11]
        runtime = Result[12]
        dataset = Result[13]
        trainPredictPlot = Result[14]
        testPredictPlot = Result[15]
        predPlot = Result[16]
        date = Result[17]
        if result_min >= dataset[-1]: # 예측값의 최소값이 실제데이터의 가장 최근 날짜보다 크면 매수
            recommend = '매수'
        elif result_min < dataset[-1]: # 예측값의 최소값이 실제데이터의 가장 최근 날짜보다 작으면 매도
            recommend = '매도'

        context = {'stock': stock,  # 분석결과 페이지에 보낼 데이터 정리
                   'result': result,
                   'result_d1': result_d1,
                   'result_d2': result_d2,
                   'result_d3': result_d3,
                   'result_d4': result_d4,
                   'result_d5': result_d5,
                   'result_d6': result_d6,
                   'result_d7': result_d7,
                   'result_max': result_max,
                   'result_min': result_min,
                   'train_RMSE': train_RMSE,
                   'test_RMSE': test_RMSE,
                   'runtime': runtime,
                   'dataset': dataset,
                   'trainPredictPlot': trainPredictPlot,
                   'testPredictPlot': testPredictPlot,
                   'predPlot': predPlot,
                   'date': date,
                   'start': start,
                   'end': end,
                   'recommend' : recommend
                   }
        return render(request, 'stockpredapp/stock_result.html', context)
    except:
        context = {'stock':stock}
        return render(request, 'stockpredapp/error.html', context)

# def error(request):
#     return render(request, 'stockpredapp/error.html')


def rnn(code, start, end):  # 순환신경망(RNN)분석 함수
    s = time.time() # 분석 시작 시간
    df = fdr.DataReader(symbol=code, start=start, end=end).reset_index() # 데이터 크롤링
    date = df['Date'] # 날짜 데이터 추출
    date = list(date) # 리스트 변환
    for i in range(len(date)): # datetime -> str 변환
        date[i] = date[i].strftime("%Y-%m-%d")
    date.append('d+1')
    date.append('d+2')
    date.append('d+3')
    date.append('d+4')
    date.append('d+5')
    date.append('d+6')
    date.append('d+7')

    dataset = df['Close'].values  # 종가 데이터 추출
    dataset = dataset.reshape(dataset.shape[0], 1)  # 1차원배열을 2차원으로 변경
    dataset = dataset.astype('float32')  # int -> float변환
    scaler = MinMaxScaler(feature_range=(0, 1))  # 최대값을 1로 설정
    Dataset = scaler.fit_transform(dataset)
    train_data, test_data = train_test_split(Dataset, test_size=0.2, shuffle=False)  # 8:2로 tarin, test 분리

    def create_dataset(dataset, look_back):  # 종속변수와 독립변수를 생성하는 함수
        x_data = []  # 빈 리스트 생성
        y_data = []

        for i in range(len(dataset) - look_back):
            data = dataset[i: (i + look_back), 0]
            x_data.append(data)
            y_data.append(dataset[i + look_back, 0])
        return np.array(x_data), np.array(y_data)

    look_back = 7  # 7개의 데이터로 예측
    x_train, y_train = create_dataset(train_data, look_back)  # train_data 생성
    x_test, y_test = create_dataset(test_data, look_back)  # test 데이터 생성

    X_train = np.reshape(x_train, (x_train.shape[0], 1, x_train.shape[1]))  # 3차원으로 변경
    X_test = np.reshape(x_test, (x_test.shape[0], 1, x_test.shape[1]))  # 3차원으로 변경

    model = Sequential()  # model 옵션
    model.add(SimpleRNN(3, input_shape=(1, look_back)))
    model.add(Dense(1, activation="linear"))
    model.compile(loss='mse', optimizer='adam')

    model.fit(X_train, y_train, epochs=epochs, batch_size=1, verbose=1)  # train_data학습

    trainPredict = model.predict(X_train)  # train_data를 이용하여 예측
    testPredict = model.predict(X_test)  # test_data를 이용하여 예측

    TrainPredict = scaler.inverse_transform(trainPredict)  # Min-Max변환된 값을 원래대로 되돌림
    Y_train = scaler.inverse_transform([y_train])  # Min-Max변환된 값을 원래대로 되돌림
    TestPredict = scaler.inverse_transform(testPredict)  # Min-Max변환된 값을 원래대로 되돌림
    Y_test = scaler.inverse_transform([y_test])  # Min-Max변환된 값을 원래대로 되돌림

    train_RMSE = math.sqrt(mean_squared_error(Y_train[0], TrainPredict[:, 0]))  # train_RMSE
    train_RMSE = round(train_RMSE, 2)
    test_RMSE = math.sqrt(mean_squared_error(Y_test[0], TestPredict[:, 0]))  # test_RMSE
    test_RMSE = round(test_RMSE, 2)

    x_pred = np.zeros(look_back * look_back, dtype=float)  # 예측값을 저장할 array생성
    x_pred = x_pred.reshape(look_back, 1, look_back)  # 3차원으로 변환

    for i in range(look_back):
        if i == 0:
            x_pred[0][0][:-1] = Dataset[-6:].reshape(6)  # 최근 6일 데이터를 pred의 1번째 row, 1~6번째 인덱스에 저장
            x_pred[0][0][-1] = model.predict(
                Dataset[-7:].reshape(1, 1, look_back))  # 최근 7일 데이터를 이용한 예측값을 pred의 1번째 row, 7번째 인덱스에 저장
        elif i > 0:
            x_pred[i][0][:-1] = x_pred[i - 1][0][1:]  # pred의 이전 row의 2~7번째 데이터를 다음 row의 1~6번째 인덱스에 저장
            x_pred[i][0][-1] = model.predict(
                x_pred[[i - 1]])  # pred의 이전 row의 1~7번째 데이터를 이용하여 데이터 예측 후, 다음 row의 7번재 인덱스에 저장

    trainPredictPlot = np.zeros(len(dataset) + 7) # 시각화를 위한 array 생성

templates/stockpredapp/error.html
{% extends 'base.html' %}
{% load stockpredapp_filter %}
{% block content %}
{% load static %}
<p></p>
<div class="container" style="text-align : center;">
    <img src="https://t1.daumcdn.net/cfile/tistory/99BB66425DFFA2EA30" alt="My Image" width="700" height="500">
    <p></p>
    <h4 class="font-center text-white bg-primary">{{ stock }}(은)는 지원하지 않는 종목입니다.</h4>
    <h4 class="font-center text-white bg-primary">5초 후 종목 선택 화면으로 되돌아갑니다.</h4>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script>
   $(document).ready(function(){
        setTimeout(function(){
            if (window.location == 'http://127.0.0.1:8000/stockpredapp/{{stock.id}}/' ) {
            window.location.href='http://127.0.0.1:8000/stockpredapp/';}}, 5000)
        })
</script>

{% endblock %}

templates/stockpredapp/loading.html
{% extends 'base.html' %}
{% load stockpredapp_filter %}
{% block content %}
{% load static %}
<p></p>
<div class="container" style="text-align : center;">
    <img src="https://cdn.ppomppu.co.kr/zboard/data3/2020/1009/m_20201009164318_cuiyazqx.gif" alt="My Image" width="700" height="500">
    <p></p>
    <h3 class="font-center text-white bg-primary">{{ market }}의 {{name}}(을)를 분석중입니다. 환경에 따라 최대 60초 소요될 수 있습니다.</h3>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script>
   $(document).ready(function(){
        setTimeout(function(){
            if (window.location == 'http://127.0.0.1:8000/stockpredapp/loading/{{stock_id}}/' ) {
            window.location.href='http://127.0.0.1:8000/stockpredapp/{{stock_id}}';}})
        })
</script>

{% endblock %}

templates/stockpredapp/main_loading.html
{% extends 'base.html' %}
{% load stockpredapp_filter %}
{% block content %}
{% load static %}
<p></p>
<div class="container" style="text-align : center;">
    <img src="https://i.pinimg.com/originals/7b/8e/00/7b8e00e3534bdf4c3118fe01a3c2df83.gif" alt="My Image" width="700" height="500">
    <p></p>
    <h3 class="font-center text-white bg-primary">데이터 수집 중입니다. 잠시만 기다려주세요.</h3>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script>
   $(document).ready(function(){
        setTimeout(function(){
            if (window.location == 'http://127.0.0.1:8000/' ) {
            window.location.href='http://127.0.0.1:8000/stockpredapp/jisu/';}})
        })
</script>

{% endblock %}

templates/stockpredapp/main_loading2.html
{% extends 'base.html' %}
{% load stockpredapp_filter %}
{% block content %}
{% load static %}
<p></p>
<div class="container" style="text-align : center;">
    <img src="https://i.pinimg.com/originals/7b/8e/00/7b8e00e3534bdf4c3118fe01a3c2df83.gif" alt="My Image" width="700" height="500">
    <p></p>
    <h3 class="font-center text-white bg-primary">데이터 수집 중입니다. 잠시만 기다려주세요.</h3>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script>
   $(document).ready(function(){
        setTimeout(function(){
            if (window.location == 'http://127.0.0.1:8000/stockpredapp/main_loading2/' ) {
            window.location.href='http://127.0.0.1:8000/stockpredapp/jisu/';}})
        })
</script>

{% endblock %}

templates/stockpredapp/stock_list.html
{% extends 'base.html' %}
{% load stockpredapp_filter %}
{% block content %}
{% load static %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<style>
.loader {
  border: 16px solid #f3f3f3; /* Light grey */
  border-top: 16px solid #3498db; /* Blue */
  border-radius: 50%;
  width: 120px;
  height: 120px;
  animation: spin 2s linear infinite;
  position:fixed;
  top:50%;
  left:50%;
  transform:translate(-50%, -50%);
}

@keyframes spin {
  0% { transform: translate(-50%, -50%) rotate(0deg); }
  100% { transform: translate(-50%, -50%) rotate(360deg); }
}
</style>
<div class="loader"></div>
<script>
    $(window).load(function(){
        $('.loader').delay(300).fadeOut();
        });
</script>


<link rel="stylesheet" type="'text/css" href="{% static 'bootstrap.min.css' %}">
<div class="container my-3">
    <div class="row justify-content-end my-3">
        <div class="col-4 input-group">
            <input type="text" class="form-control kw1 me-sm-2" value="{{ kw1|default_if_none:'' }}">
            <div class="input-group-append">
                <button class="btn btn-secondary my-2 my-sm-0" type="button" id="btn_search1">종목 검색</button>

            </div>
            <a class="page-link" href="{% url 'stockpredapp:random_pred' %}" title="랜덤으로 종목을 선택하여 분석합니다.">랜덤 분석</a>
        </div>
    </div>
    <MARQUEE class="text-info"><em>
        종목이름, 종목코드, 상장구분으로 검색 가능합니다. 상장 구분은
        <a href="https://ko.wikipedia.org/wiki/%EC%BD%94%EC%8A%A4%ED%94%BC">KOSPI</a>,
        <a href="https://ko.wikipedia.org/wiki/%EC%BD%94%EC%8A%A4%EB%8B%A5">KODAQ</a>,
        <a href="https://ko.wikipedia.org/wiki/%EB%82%98%EC%8A%A4%EB%8B%A5">NASDAQ</a>,
        <a href="https://ko.wikipedia.org/wiki/S%26P_500">S&P500</a>,
        <a href="https://ko.wikipedia.org/wiki/%EB%89%B4%EC%9A%95_%EC%A6%9D%EA%B6%8C%EA%B1%B0%EB%9E%98%EC%86%8C">NYSE</a>,
        <a href="https://ko.wikipedia.org/wiki/%EC%95%84%EB%A9%94%EB%A6%AC%EC%B9%B4_%EC%A6%9D%EA%B6%8C%EA%B1%B0%EB%9E%98%EC%86%8C">AMEX</a>
        으로 구분되어있습니다.
    </em></MARQUEE>

    <table class="table">
        <thead>
        <tr class="table-secondary">
            <th>번호</th>
            <th>종목명</th>
            <th>종목코드</th>
            <th>상장구분</th>
            <th>사업분야</th>
            <th>홈페이지</th>
        </tr>
        </thead>
        <tbody>
        {% if stock_list %}
        {% for stock in stock_list %}
        <tr class>
            <td>
                <!-- 번호 = 전체건수 - 시작인덱스 - 현재인덱스 + 1 -->
                {{ stock_list.paginator.count|sub:stock_list.start_index|sub:forloop.counter0|add:1 }}
            </td>
            <td>
                <a href="{% url 'stockpredapp:loading' stock.id %}">{{ stock.stock_name }}</a>
            </td>
            <td>
                <a href="{% url 'stockpredapp:loading' stock.id %}">{{ stock.stock_code }}</a>
            </td>
            <td>{{ stock.market }}</td>
            <td>{{ stock.sector }} / {{ stock.industry}}</td>
            <td>
                <a href="{{ stock.homepage }}">{{ stock.homepage }}</a>
            </td>
        </tr>
        {% endfor %}
        {% else %}
        <tr class ="text-center">
            <td colspan="7">종목이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <!--페이징 처리 시작-->
    <ul class="pagination justify-content-center">
        <!--이전 페이지-->
        {% if stock_list.has_previous %}
        <li class="page-item">
            <a class="page-link" data-page1="{{ stock_list.previous_page_number }}" href="#">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
             <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!--페이지 리스트-->
        {% for page_number in stock_list.paginator.page_range %}
        {% if page_number >= stock_list.number|add:-5 and page_number <= stock_list.number|add:5 %}
            {% if page_number == stock_list.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" data-page1="{{ page_number }}" href="#">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" data-page1="{{ page_number }}" href="#">{{ page_number }}</a>
            </li>
            {% endif %}
        {% endif %}
        {% endfor %}
        <!--다음페이지-->
        {% if stock_list.has_next %}
        <li class="page-item">
            <a class="page-link" data-page1="{{ stock_list.next_page_number }}" href="#">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!--페이징 처리 끝-->
</div>
<form id="searchForm1" method="get" action="{% url 'stockpredapp:s_index' %}">
    <input type="hidden" id="kw1" name="kw1" value="{{ kw1|default_if_none:'' }}">
    <input type="hidden" id="page1" name="page1" value="{{ page1 }}">
</form>
{% endblock %}
{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $(".page-link").on('click', function() {
        $("#page1").val($(this).data("page1"));
        $("#searchForm1").submit();
    });

    $("#btn_search1").on('click', function() {
        $("#kw1").val($(".kw1").val());
        $("#page1").val(1);  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
        $("#searchForm1").submit();
    });
});
</script>
{% endblock %}

<!--{% if stock_list %}-->
<!--    <ul>-->
<!--    {% for stock in stock_list %}-->
<!--        <li><a href="{% url 'stockpredapp:result' stock.id %}">{{ stock.stock_name }}</a></li>-->

<!--    {% endfor %}-->
<!--    </ul>-->
<!--{% else %}-->
<!--    <p>종목이 없습니다.</p>-->
<!--{% endif %}-->